Import Packages 

In [7]:
import pandas as pd
import numpy as np

# Matrix & Vector Learning

In [14]:
my_matrix = np.matrix([[10, 20, 30], [33, 22, 11], [2 , 1, 3]])
my_matrix2 = np.matrix([[10, 20, 30], [33, 22, 11], [2 , 1, 3]])
my_matrix + my_matrix2

matrix([[20, 40, 60],
        [66, 44, 22],
        [ 4,  2,  6]])

In [16]:
my_product = my_matrix ** 2
my_product

matrix([[ 820,  670,  610],
        [1078, 1155, 1265],
        [  59,   65,   80]])

In [19]:
vector_k1 = np.array([12, 17, 26])
vector_k2 = np.array([7, 10, 90])
vector_k1 * vector_k2

array([  84,  170, 2340])

In [21]:
my_dot_product = vector_k1.dot(vector_k2)
my_dot_product

2594

In [35]:
vector_e1 = np.array([1,5,6])
vector_e2 = np.array([7,4,-1])

# dot product is the sum of the product of both vectors
my_edot_product= vector_e2.dot(vector_e1)
my_edot_product

21

In [32]:
vector_f1 = np.array([[1,5,6],[3,2,2]])
vector_f2 = np.array([7,4,-1])

vector_f1 * vector_f2

array([[ 7, 20, -6],
       [21,  8, -2]])

In [39]:
# norm is the magnitude of the line 
norm = np.linalg.norm(vector_f2)
norm

8.12403840463596

In [40]:
norm_test = vector_f2.dot((vector_f2)**1/2)
norm_test

33.0